Right menu key
wmjordan/PDFPatcher pull request #57
Opened 2022-01-18 10:24 UTC by ShoJinto

自己的issue还是自己来解决。

为程序添加鼠标右键菜单
添加右键菜单需要在注册表的HKEY_CLASSES_ROO节点下操作
原本打算使用System.Security进行提权，但是尝试多种方法均失败，所以采取了修改app.manifest来实现
```xml
<requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
改为
<requestedExecutionLevel level="highestAvailable" uiAccess="false" />
```
有关注册表的描述：https://www.c-sharpcorner.com/UploadFile/f9f215/windows-registry/
注册表的提权操作见：https://docs.microsoft.com/zh-cn/dotnet/api/system.security.accesscontrol.registrysecurity?view=net-6.0#methods

resolves #13

2022-01-18 11:57 UTC, wmjordan requested changes
最好能避免对原代码不必要的修改

2022-01-18 11:57 UTC, wmjordan commented on App/CppProperties.json
> +{
这个文件是干什么用的呢？不需要这个文件吧？

2022-01-18 11:57 UTC, wmjordan commented on App/Common/RightKeyHelper.cs
> +		private static RegistryKey root = Registry.ClassesRoot;
是否可能改用“HKEY_CURRENT_USER\Software\Classes”，避免要求管理员权限

2022-01-18 12:35 UTC, ShoJinto commented on App/Common/RightKeyHelper.cs
> +		private static RegistryKey root = Registry.ClassesRoot;
嗯嗯，这个我得继续查下资料，抽时间继续改进。

2022-01-18 14:33 UTC, closed without merging

2022-01-18 14:44 UTC, calcitem commented on App/Common/RightKeyHelper.cs
> +		private static RegistryKey root = Registry.ClassesRoot;
改进后使用强制性推送即可，不需要关闭PR，详情可参阅项目的贡献者指南。

2022-01-19 02:07 UTC, ShoJinto commented on App/Common/RightKeyHelper.cs
> +		private static RegistryKey root = Registry.ClassesRoot;
> 改进后使用强制性推送即可，不需要关闭PR，详情可参阅项目的贡献者指南。

不是关闭，是当时分支重命名引起的